import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layouts are used to wrap your page content and typically include elements that remain consistent across different pages, such as headers, footers, navigation menus, and sidebars. Using layouts helps maintain a uniform look and feel throughout your application and makes it easier to manage and update shared components.


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
